/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:6d8a3887-5057-4f35-9554-7897b4a4019a",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_otAjLBSJ7",
    "aws_user_pools_web_client_id": "1n05m5q0f98a32cq1el77r8h43",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6nbkvuzpgbhrtilpdqqwpvl6sa.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cfepekjtpjby3evgqqnvndgqai",
    "aws_user_files_s3_bucket": "viraasat9975488b39cb41b18a39c90ce4068c105cfb4-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;